version: "3.3"
services:
  alist:
    container_name: alist
    image: "xhofe/alist:latest"
    restart: always
    ports:
      - "5244:5244"
    volumes:
      - "./data:/opt/alist/data"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
