services:
  pingvin-share:
    container_name: pingvin-share
    image: "stonith404/pingvin-share:latest"
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"
