version: "3.5"
services:
  yourls-db:
    container_name: yourls-db
    image: mysql
    restart: always
    volumes:
      - ./mysql/db/:/var/lib/mysql
      - ./mysql/conf/:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=yourls-db
      - MYSQL_USER=yourls-db
      - MYSQL_PASSWORD=yourls-db
      - MYSQL_ROOT_PASSWORD=yourls-db

  yourls:
    container_name: yourls
    image: yourls:latest
    restart: always
    ports:
      - "8200:80"
    volumes:
      - ./data/:/var/www/html
    environment:
      YOURLS_DB_HOST: yourls-db
      YOURLS_DB_USER: yourls-db
      YOURLS_DB_PASS: yourls-db
      YOURLS_DB_NAME: yourls-db
      YOURLS_USER: admin #面板登录用户名
      YOURLS_PASS: admin #面板登录密码
      YOURLS_SITE: https://example.com #面板域名
      YOURLS_HOURS_OFFSET: 8
    links:
      - yourls-db:yourls-db
