services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/etc/redis/config/redis.conf #确保在启动之前 redis.conf 已在 ./config/ 中配置好。
      - ./data:/data
      - ./log:/log
    command: redis-server /etc/redis/config/redis.conf
    environment:
      - TZ=Asia/Shanghai
