version: "3"
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: "chishin/nginx-proxy-manager-zh:latest"
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
